Controllers/StateProvinceController.cs
using Aspose.Cells;
using PersoneManagement.Web.Models.DTO;
using PersoneManagement.Web.Models.Interfaces;
using PersoneManagement.Web.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace PersoneManagement.Web.Controllers
{
    public class StateProvinceController : Controller
    {
        private IStateProvinceRepository _stateProvinceRepository;
        private IExcelService _exportExcelService;

        public StateProvinceController() : this(new StateProvinceRepository(), new ExcelService()) { }

        public StateProvinceController(IStateProvinceRepository stateProvinceRepository, 
            IExcelService exportExcelService) 
        {
            _stateProvinceRepository = stateProvinceRepository;
            _exportExcelService = exportExcelService;
        }

        // GET: StateProvince
        public ActionResult Index()
        {
            //var stateProvincesData = _stateProvinceRepository.GetAll();

            return View();
        }

        public JsonResult GetStates()
        {
            //var stateProvincesData = _stateProvinceRepository.GetStateProvinces();

            var stateProvincesData = _stateProvinceRepository.GetAll();

            return Json(new {data = stateProvincesData}, JsonRequestBehavior.AllowGet);
        }

        // GET: StateProvince/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: StateProvince/Create
        public ActionResult Create()
        {
            ShowRegionsList();

            var stateProvinceDTO = new StateProvinceDTO();

            stateProvinceDTO.SalesTerritorriesDdl = new List<SelectListItem>();

            return View(stateProvinceDTO);
        }

        // POST: StateProvince/Create
        [HttpPost]
        public ActionResult Create(StateProvinceDTO stateProvinceDTO)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _stateProvinceRepository.InsertStateProvince(stateProvinceDTO);
                    TempData["SuccessMessage"] = "Customer created succesfully";
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex) 
            {
                ShowRegionsList();

                ShowTerritorryListRePop(stateProvinceDTO);
                
                ModelState.AddModelError("", "Unable to Save due to " + ex.Message);
                return View(stateProvinceDTO);
            }
        }

        // GET: StateProvince/Edit/5
        public ActionResult Edit(int id)
        {
            var result = _stateProvinceRepository.GetStateProvinceById(id);

            if (result == null)
            {
                return HttpNotFound();
            }

            StateProvinceDTO transform = RepopulateForm(result);

            return View(transform);
        }

        private StateProvinceDTO RepopulateForm(StateProvinceService.StateProvinceDTO result)
        {
            var transform = new StateProvinceDTO
            {
                StateProvinceID = result.StateProvinceID,
                StateProvinceCode = result.StateProvinceCode,
                CountryRegionCode = result.CountryRegionCode,
                IsOnlyStateProvinceFlag = result.IsOnlyStateProvinceFlag,
                Name = result.Name,
                TerritoryID = result.TerritoryID,
                rowguid = result.rowguid,
                ModifiedDate = DateTime.Now,

            };

            ShowRegionsList();



            transform.SalesTerritorriesDdl = _stateProvinceRepository.GetAllTerritories()
               .Where(t => t.CountryRegionCode == result.CountryRegionCode)
              .Select(t => new SelectListItem
              {
                  Value = t.TerritoryID.ToString(),
                  Text = t.Name,
                  Selected = t.CountryRegionCode == result.CountryRegionCode

              }).ToList();
            return transform;
        }

        // POST: StateProvince/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, StateProvinceDTO stateProvinceDTO)
        {
            var existingData = _stateProvinceRepository.GetStateProvinceById(id);

            try
            {
                // TODO: Add update logic here
                

                if (existingData == null)
                {
                    return HttpNotFound();
                }

                if (ModelState.IsValid)
                {
                    _stateProvinceRepository.UpdateStateProvince(stateProvinceDTO, existingData.rowguid);
                    TempData["SuccessMessage"] = "State Province Updated succesfully";
                }

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to update due to " + ex.Message);

                StateProvinceDTO transform = RepopulateForm(existingData);

                return View(transform);
            }
        }

        // GET: StateProvince/Delete/5
        public ActionResult Delete(int id)
        {


            return View();
        }

        // POST: StateProvince/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var existingData = _stateProvinceRepository.GetStateProvinceById(id);

                if (existingData == null)
                {
                    return HttpNotFound();
                }

                _stateProvinceRepository.DeleteStateProvince(id);

                return Json(new
                {
                    success = true
                }
                );


            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", "Unable to update due to " + ex.Message);
                return Json(new
                {
                    success = false
                }
                );
            }
        }

        public ActionResult StateProvinceExportToExcel()
        {

            var workBook = _exportExcelService.StateProvinceExportToExcel();

            //Save Workbook
            var stream = new System.IO.MemoryStream();

            workBook.Save(stream, SaveFormat.Xlsx);

            //return
            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "StateProvince.xlsx");

        }

        public ActionResult Upload()
        {
            return View();
        }

        [HttpPost]
        public ActionResult StateProvinceImportToExcel(HttpPostedFileBase file)
        {

            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    //ImportStateProvinceFromExcel(file);

                    _exportExcelService.ImportStateProvinceExcelToDatabase(file);
                }

                TempData["SuccessMessage"] = "Data imported Succesfully";

                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to import due to " + ex.Message);
                return View();
            }

        }





        public JsonResult ShowTerritorryList(string regionCode)
        {
            var dropDownTerriotryList = _stateProvinceRepository.GetTerritoriesByRegionCode(regionCode)
                .Select(t => new SelectListItem
                {
                    Value = t.TerritoryID.ToString(),
                    Text = t.Name
                });

            return Json(dropDownTerriotryList, JsonRequestBehavior.AllowGet);
        }

        public void ShowTerritorryListRePop(StateProvinceDTO stateProvinceDTO)
        {
            stateProvinceDTO.SalesTerritorriesDdl = _stateProvinceRepository.GetAllTerritories()
                           .Where(t => t.CountryRegionCode == stateProvinceDTO.CountryRegionCode)
                          .Select(t => new SelectListItem
                          {
                              Value = t.TerritoryID.ToString(),
                              Text = t.Name,
                              Selected = t.CountryRegionCode == stateProvinceDTO.CountryRegionCode

                          }).ToList();

        }

        public void ShowRegionsList()
        {
            var dropDownRegions = _stateProvinceRepository.GetCountryRegions();
            var dropDownTerritories = _stateProvinceRepository.GetAllTerritories();


            ViewBag.RegionList = new SelectList(dropDownRegions, "CountryRegionCode", "Name");
        }


    }
}

Views/StateProvince/Create.cshtml
@model PersoneManagement.Web.Models.DTO.StateProvinceDTO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create State Province</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.CountryRegionCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.CountryRegionCode, (SelectList)ViewBag.RegionList, "Select Region",
               new { @class = "form-control", @id = "RegionsDropdown" })
                @Html.ValidationMessageFor(model => model.CountryRegionCode, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.TerritoryID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.TerritoryID, Model.SalesTerritorriesDdl, "Select Territory", new { @class = "form-control", @id = "TerritoryDropdown" })
                @Html.ValidationMessageFor(model => model.TerritoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateProvinceCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.StateProvinceCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StateProvinceCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOnlyStateProvinceFlag, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsOnlyStateProvinceFlag)
                    @Html.ValidationMessageFor(model => model.IsOnlyStateProvinceFlag, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function () {
        $('#RegionsDropdown').change(function () {
            var categoryId = $(this).val();
            $.getJSON('@Url.Action("ShowTerritorryList", "StateProvince")', { regionCode: categoryId }, function (data) {
                var items = '<option >Select Territory</option>';
                $.each(data, function (i, product) {
                    items += '<option value="' + product.Value + '">' + product.Text + '</option>';
                });
                $('#TerritoryDropdown').html(items);
            });
        });
    });
    </script>
}

Views/StateProvince/Edit.cshtml
@model PersoneManagement.Web.Models.DTO.StateProvinceDTO

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>StateProvinceDTO</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.StateProvinceID)
    @Html.HiddenFor(model => model.rowguid)

    <div class="form-group">
        @Html.LabelFor(model => model.CountryRegionCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.CountryRegionCode, (SelectList)ViewBag.RegionList, "Select Region",
           new { @class = "form-control", @id = "RegionsDropdown" })
            @Html.ValidationMessageFor(model => model.CountryRegionCode, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.TerritoryID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.TerritoryID, Model.SalesTerritorriesDdl, "Select Territory", new { @class = "form-control", @id = "TerritoryDropdown" })
            @Html.ValidationMessageFor(model => model.TerritoryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StateProvinceCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.StateProvinceCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.StateProvinceCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IsOnlyStateProvinceFlag, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.IsOnlyStateProvinceFlag)
                @Html.ValidationMessageFor(model => model.IsOnlyStateProvinceFlag, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
    $(document).ready(function () {
        $('#RegionsDropdown').change(function () {
            var categoryId = $(this).val();
            $.getJSON('@Url.Action("ShowTerritorryList", "StateProvince")', { regionCode: categoryId }, function (data) {
                var items = '<option >Select Territory</option>';
                $.each(data, function (i, product) {
                    items += '<option value="' + product.Value + '">' + product.Text + '</option>';
                });
                $('#TerritoryDropdown').html(items);
            });
        });
    });
    </script>
}

Views/StateProvince/Index.cshtml
@model IEnumerable<PersoneManagement.Web.StateProvinceService.StateProvinceDTO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css">
    <style>
        .dataTables_wrapper {
            width: 900px;
        }

            .dataTables_wrapper .dataTables_paginate {
                float: none;
                text-align: center;
            }

            .dataTables_wrapper .dataTables_info {
                float: left;
                padding-top: 0.755em;
            }

            .dataTables_wrapper .bottom {
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
    </style>
}

<h2>State Province</h2>

<div style="display:block">
    <a href="@Url.Action("Create", "StateProvince")" class="btn btn-primary">
        + Add State Province
    </a>
</div>

<table class="table" id="stateProvinceData" style="width:100%">
    <thead>
        <tr>
            <th>Actions</th>
            <th>No. </th>
            <th>
                Country Name
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                Code
            </th>
            <th>
                Territorry
            </th>
            <th>
                Flag
            </th>
            <th>
                Modified Date
            </th>
        </tr>
    <thead>

</table>

<a href="@Url.Action("StateProvinceExportToExcel","StateProvince" )" class="btn btn-primary">
    Export to Excel
</a>


@using (Html.BeginForm("StateProvinceImportToExcel", "StateProvince", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <input type="file" name="file" accept=".xlsx, .xls" required />
    </div>
    <br />

    <button class="btn btn-primary" type="submit">Upload</button>
}


@section scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#stateProvinceData').DataTable({
                "ajax": {
                    "url": "/StateProvince/GetStates",
                    "type": "GET",
                    "datatype": "json"
                },
                "columns": [
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            var editLink = '@Url.Action("Edit", "StateProvince", new { id = "PLACEHOLDER"})'.replace("PLACEHOLDER", row.StateProvinceID);

                            return '<div class="btn-group">' +
                                '<a href="' + editLink + '" class="btn btn-primary" data-id="' + row.StateProvinceID+ '" id="editButton" style="margin-right: 5px;">' +
                                'Edit</a>' +
                                '<button id="deleteButton" class="btn btn-danger deleteButton" data-id="' + row.StateProvinceID + '">' +
                                'Delete</button>' +
                                '</div>'

                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;  // Display the row number (meta.row is zero-indexed)
                        }
                    },
                    { "data": "CountryRegionNames" },
                    { "data": "Name" },
                    { "data": "StateProvinceCode" },
                    { "data": "TerritorryNames" },
                    { "data": "IsOnlyStateProvinceFlag" },
                    {
                        "data": "ModifiedDate",
                        "render": function (data, type, row) {
                            return moment(data).format('DD-MMM-YYYY HH:mm:ss');
                        }
                    },
                ],
/*                "order": [[0, "desc"]],*/
                "dom": '<"top"f>rt<"bottom"lpi><"clear">', // search on the top right, show entries, paging, showing on the bottom
                "pagingType": "full_numbers",
                "scrollY": "400px",
                "scrollX": true,
                "scrollCollapse": true,
                "fixedHeader": true,
                //"pagingType": "simple_numbers",
                "pageLength": 10,
                "lengthMenu": [10, 25, 50, 100],
                "scrollY": "400px",
                "scrollX": true,
                "scrollCollapse": true,
                "fixedHeader": true,
                "language": {
                    "paginate": {
                        "previous": "Previous",
                        "next": "Next",
                        "first": "<<",
                        "last": ">>"
                    }
                }
            });
        });

        ////Use this for datatables, becase the buttons are created dynamically
        $(document).on('click', '#deleteButton', function () {
            const itemId = $(this).data('id'); // Retrieve the ID of the item to delete

            Swal.fire({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this item!",
                icon: "warning",
                showCancelButton: true, // Enable the cancel button
                buttons: true,
                dangerMode: true,
            })
                .then((result) => {
                    if (result.isConfirmed) {
                        // Make an AJAX call to delete the item
                        $.ajax({
                            url: '/StateProvince/Delete', // URL of your Delete method
                            type: 'POST', // Use POST for data modification
                            data: { id: itemId }, // Pass the ID as data
                            success: function (response) {
                                if (response.success) {
                                    Swal.fire("Deleted!", response.message, "success").then(() => {
                                        $("#stateProvinceData").DataTable().ajax.reload(); // Reload the page or update UI
                                    });
                                } else {
                                    Swal.fire("Error!", response.message, "error");
                                }
                                Swal.fire("Poof! Your item has been deleted!", {
                                    icon: "success",
                                }).then(() => {
                                    // Optional: Reload the page or update the UI
                                    location.reload();
                                });
                            },
                            error: function (error) {
                                Swal.fire("Error!", "Unable to delete the item " + response.message + " . Please try again.", "error");
                            }
                        });
                    } else if (result.dismiss == Swal.DismissReason.cancel) {
                        Swal.fire("Your item is safe!");
                    }
                });
        });

        $(document).ready(function () {
            var table = $('#stateProvinceData').DataTable();

            // Unbind the default search event
            $('#stateProvinceData_filter input').unbind();

            // Bind a new event handler
            $('#stateProvinceData_filter input').on('keyup', function (e) {
                var value = $(this).val();
                if (value.length >= 3 || value.length === 0) {
                    table.search(value).draw();
                }
            });
        });
    </script>

}

Views/StateProvince/Upload.cshtml
@{
    ViewBag.Title = "Upload";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Upload Excel File</h2>