Controllers/AddressController.cs
using Aspose.Cells;
using Microsoft.Ajax.Utilities;
using PersoneManagement.Web.Models;
using PersoneManagement.Web.Models.DTO;
using PersoneManagement.Web.Models.Interfaces;
using PersoneManagement.Web.Models.Repositories;
using PersoneManagement.Web.StateProvinceService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc; 

namespace PersoneManagement.Web.Controllers
{
    public class AddressController : Controller
    {
        private IAddressRepository _addressRepository;
        private IPersonRepository _personRepository;
        private IStateProvinceRepository _stateProvinceRepository;
        private IExcelService _excelService;

        public AddressController() : this(new AddressRepository(), new PersonRepository(), new StateProvinceRepository(), new ExcelService() ) { }
        public AddressController(IAddressRepository addressRepository, 
            IPersonRepository personRepository, 
            IStateProvinceRepository stateProvinceRepository,
            IExcelService excelService)
        {
            _addressRepository = addressRepository;
            _personRepository = personRepository;
            _stateProvinceRepository = stateProvinceRepository;
            _excelService = excelService;
        }

        // GET: Address
        public ActionResult Index(int personID)
        {
            ViewBag.PersonID = personID;

       

            ViewBag.Name = _personRepository.GetFullName(personID);

            return View();
        }

        public JsonResult GetAddress(int businessEntityId)
        {
            var addressData = _addressRepository.GetAddressesByBusinessId(businessEntityId);

            var json = Json(new { data = addressData }, JsonRequestBehavior.AllowGet);

            json.MaxJsonLength = int.MaxValue;

            return json;
        }


        // GET: Address/Create
        public ActionResult Create(int personID)
        {

            ShowProvinceList();
            ShowTypesList(); 

            return View();
        }

        // POST: Address/Create
        [HttpPost]
        public ActionResult Create(AddressDTO addressDTO, int personID)
        {
            try
            {

                // TODO: Add insert logic here
                _addressRepository.AddAddress(addressDTO, personID);


                TempData["SuccessMessage"] = "Customer created succesfully";
                return RedirectToAction("Index", new {personID = personID});
            }
            catch (Exception ex) 
            {
                ShowProvinceList();
                ShowTypesList();
                ModelState.AddModelError("", "Error creating person: " + ex.Message);
                return View();
            }
        }

        // GET: Address/Edit/5
        public ActionResult Edit(int id, int personId)
        {

            var address = _addressRepository.GetAddressById(id, personId);

            if (address == null) return HttpNotFound();

            ShowProvinceList();
            ShowTypesList();

            var result = Mapping.Mapper.Map<AddressDTO>(address);

            return View(result);
        }

        // POST: Address/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, AddressDTO addressDTO, int personId)
        {
            try
            {
                // TODO: Add update logic here
                var existingData = _addressRepository.GetAddressById(id, personId);

                var existingRowGuid = existingData.rowguid;

                if (existingData == null)
                {
                    return HttpNotFound();
                }

                if (ModelState.IsValid)
                {
                    _addressRepository.UpdateAddress(addressDTO, personId, existingRowGuid);
                    TempData["SuccessMessage"] = "Address Updated succesfully";
                }

                return RedirectToAction("Index", new { personID = personId });
            }
            catch(Exception ex) 
            {
                ShowProvinceList();
                ShowTypesList();
                ModelState.AddModelError("", "Unable to update due to " + ex.Message);
                return View();
            }
        }

        // GET: Address/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Address/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, AddressDTO addressDTO, int personID)
        {
            try
            {
                // TODO: Add delete logic here

                var existingData = _addressRepository.GetAddressById(id, personID);

                if (existingData == null)
                {
                    return HttpNotFound();
                }

                _addressRepository.DeleteAddress(id, personID);

                return Json(new
                {
                    success = true
                }
                );
            }
            catch (Exception ex) 
            {
                ModelState.AddModelError("", "Unable to delete due to " + ex.Message);
                return Json(new
                {
                    success = false
                }
                );
            }
        }

        public ActionResult ExportExcel(int businessEntityId)
        {


            var workBook = _excelService.AddressExportToExcel(businessEntityId);

            var stream = new System.IO.MemoryStream();

            workBook.Save(stream, SaveFormat.Xlsx);

            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "PersonAddress.xlsx");
        }

        [HttpPost]
        public ActionResult ImportExcel(HttpPostedFileBase file, int businessEntityId)
        {
            try
            {
                if (file != null && file.ContentLength > 0)
                {
                    _excelService.ImportAddressExcelToDatabase(file, businessEntityId);
                }

                TempData["SuccessMessage"] = "Data imported Succesfully";
                return RedirectToAction("Index", new { personID = businessEntityId });
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", "Unable to import due to " + ex.Message);
                return View();
            }
        }

        public void ShowTypesList()
        {
            var dropDownType = _addressRepository.GetAddressTypes();

            ViewBag.typeList = new SelectList(dropDownType, "AddressTypeID", "Name");
        }
  

        public void ShowProvinceList()
        {
            var dropDownsProvince = _stateProvinceRepository.GetAll();

            ViewBag.provinceList = new SelectList(dropDownsProvince, "StateProvinceID", "Name");
        }
    }
}

Views/Address/Create.cshtml
@model PersoneManagement.Web.Models.DTO.AddressDTO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Address</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.AddressesTypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AddressesTypeName, (SelectList)ViewBag.typeList, "Select Type",
new { @class = "form-control", @id = "TypeDropdown" })
                @Html.ValidationMessageFor(model => model.AddressesTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateProvinceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StateProvinceID, (SelectList)ViewBag.provinceList, "Select State Province",
new { @class = "form-control", @id = "ProvinceDropDown" })
                @Html.ValidationMessageFor(model => model.StateProvinceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Address/Edit.cshtml
@model PersoneManagement.Web.Models.DTO.AddressDTO

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>AddressDTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.AddressID)

        <div class="form-group">
            @Html.LabelFor(model => model.AddressesTypeName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.AddressesTypeName, (SelectList)ViewBag.typeList, "Select Type",
    new { @class = "form-control", @id = "TypeDropdown" })
                @Html.ValidationMessageFor(model => model.AddressesTypeName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AddressLine2, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AddressLine2, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AddressLine2, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.StateProvinceID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.StateProvinceID, (SelectList)ViewBag.provinceList, "Select State Province",
    new { @class = "form-control", @id = "ProvinceDropDown" })
                @Html.ValidationMessageFor(model => model.StateProvinceID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PostalCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PostalCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PostalCode, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Address/Index.cshtml
@model IEnumerable<PersoneManagement.Web.Models.DTO.AddressDTO>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles {
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css">
    <style>
        .dataTables_wrapper {
            width: 900px;
        }

            .dataTables_wrapper .dataTables_paginate {
                float: none;
                text-align: center;
            }

            .dataTables_wrapper .dataTables_info {
                float: left;
                padding-top: 0.755em;
            }

            .dataTables_wrapper .bottom {
                display: flex;
                justify-content: space-between;
                align-items: center;
            }
    </style>
}

<h2>Address</h2>
<h3>@ViewBag.Name</h3>

<div class="btn-primary">
    <a href="@Url.Action("Create", "Address", new { personId = ViewBag.PersonID })"> Create </a>
</div>
<table class="table" id="addressData" style="width:100%">
    <thead>
        <tr>
            <th>Actions</th>
            <th>No.</th>
            <th>
                @Html.DisplayNameFor(model => model.AddressesTypeName)
            </th>
            <th>
                Address
            </th>
            <th>
                State Province
            </th>
            <th>
                @Html.DisplayNameFor(model => model.City)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PostalCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ModifiedDate)
            </th>
        </tr>
    </thead>
</table>

<a href="@Url.Action("ExportExcel","Address", new {businessEntityId = ViewBag.PersonID})" class="btn btn-primary">
    Export to Excel
</a>

@using (Html.BeginForm("ImportExcel", "Address",new { businessEntityId = ViewBag.PersonID }, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>
        <input type="file" name="file" accept=".xlsx, .xls" required />
    </div>
    <br />

    <button class="btn btn-primary" type="submit">Upload</button>
}

@section scripts {
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.29.1/moment.min.js"></script>
    <script>
        $(document).ready(function () {
            var table = $('#addressData').DataTable({
                "ajax": {
                    "url": "/Address/GetAddress?businessEntityId=" + @ViewBag.PersonID,
                    "type": "GET",

                    "datatype": "json"
                },
                "columns": [
                    {
                        "data": null,
                        "render": function (data, type, row) {
                            var editLink = '@Url.Action("Edit", "Address", new { id = "PLACEHOLDER", personId = ViewBag.PersonID })'.replace("PLACEHOLDER", row.AddressID);
                            return '<div class="btn-group">' +
                                '<a href="' + editLink + '" class="btn btn-primary" data-id="' + row.AddressID + '" id="editButton" style="margin-right: 5px;">' +
                                '<i class="fas fa-edit"></i></a>' +
                                '<button id="deleteButton" class="btn btn-danger deleteButton" data-id="' + row.AddressID + '">' +
                                '<i class="fas fa-trash-alt"></i></button>' +
                                '</div>'

                        }
                    },
                    {
                        "data": null,
                        "render": function (data, type, row, meta) {
                            return meta.row + 1;  // Display the row number (meta.row is zero-indexed)
                        }
                    },
                    { "data": "AddressesTypeName" },
                    { "data": "AddressessFullName" },
                    { "data": "StatesProvinceName" },
                    { "data": "City" },
                    {"data": "PostalCode"},
                    {
                        "data": "ModifiedDate",
                        "render": function (data, type, row) {
                            return moment(data).format('DD-MMM-YYYY HH:mm:ss');
                        }
                    },
                ],
/*                "order": [[0, "desc"]],*/
                "dom": '<"top"f>rt<"bottom"lpi><"clear">', // search on the top right, show entries, paging, showing on the bottom
                "pagingType": "full_numbers",
                "scrollY": "400px",
                "scrollX": true,
                "scrollCollapse": true,
                "fixedHeader": true,
                //"pagingType": "simple_numbers",
                "pageLength": 10,
                "lengthMenu": [10, 25, 50, 100],
                "scrollY": "400px",
                "scrollX": true,
                "scrollCollapse": true,
                "fixedHeader": true,
                "language": {
                    "paginate": {
                        "previous": "Previous",
                        "next": "Next",
                        "first": "<<",
                        "last": ">>"
                    }
                }
            });
        });


        ////Use this for datatables, becase the buttons are created dynamically
        $(document).on('click', '#deleteButton', function () {
            const itemId = $(this).data('id'); // Retrieve the ID of the item to delete

            Swal.fire({
                title: "Are you sure?",
                text: "Once deleted, you will not be able to recover this item!",
                icon: "warning",
                showCancelButton: true, // Enable the cancel button
                buttons: true,
                dangerMode: true,
            })
                .then((result) => {
                    if (result.isConfirmed) {
                        // Make an AJAX call to delete the item
                        $.ajax({
                            url: '/Address/Delete', // URL of your Delete method
                            type: 'POST', // Use POST for data modification
                            data: { id: itemId, personID: @ViewBag.PersonID }, // Pass the ID as data
                            success: function (response) {
                                if (response.success) {
                                    Swal.fire("Deleted!", response.message, "success").then(() => {
                                        $("#addressData").DataTable().ajax.reload(); // Reload the page or update UI
                                    });
                                } else {
                                    Swal.fire("Error!", response.message, "error");
                                }
                                Swal.fire("Poof! Your item has been deleted!", {
                                    icon: "success",
                                }).then(() => {
                                    // Optional: Reload the page or update the UI
                                    location.reload();
                                });
                            },
                            error: function (error) {
                                Swal.fire("Error!", "Unable to delete the item. Please try again.", "error");
                            }
                        });
                    } else if (result.dismiss == Swal.DismissReason.cancel) {
                        Swal.fire("Your item is safe!");
                    }
                });
        });
    </script>

}